# coding: utf-8

# flake8: noqa
"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: crservice@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.component import Component
from swagger_client.models.dataset import Dataset
from swagger_client.models.dataset_definition import DatasetDefinition
from swagger_client.models.dataset_identity import DatasetIdentity
from swagger_client.models.dataset_locales import DatasetLocales
from swagger_client.models.dataset_update import DatasetUpdate
from swagger_client.models.endpoint import Endpoint
from swagger_client.models.endpoint_data import EndpointData
from swagger_client.models.endpoint_data_definition import EndpointDataDefinition
from swagger_client.models.endpoint_definition import EndpointDefinition
from swagger_client.models.endpoint_metadata_update import EndpointMetadataUpdate
from swagger_client.models.error_content import ErrorContent
from swagger_client.models.error_detail import ErrorDetail
from swagger_client.models.health_status_response import HealthStatusResponse
from swagger_client.models.i_model_definition_v2 import IModelDefinitionV2
from swagger_client.models.inner_error import InnerError
from swagger_client.models.model import Model
from swagger_client.models.model_identity import ModelIdentity
from swagger_client.models.model_training_locales import ModelTrainingLocales
from swagger_client.models.model_update import ModelUpdate
from swagger_client.models.speech_endpoint_definition import SpeechEndpointDefinition
from swagger_client.models.speech_model_definition import SpeechModelDefinition
from swagger_client.models.test import Test
from swagger_client.models.test_definition import TestDefinition
from swagger_client.models.test_update import TestUpdate
from swagger_client.models.transcription import Transcription
from swagger_client.models.transcription_definition import TranscriptionDefinition
from swagger_client.models.transcription_update import TranscriptionUpdate
from swagger_client.models.voice_test import VoiceTest
from swagger_client.models.voice_test_definition import VoiceTestDefinition
from swagger_client.models.web_hook_configuration import WebHookConfiguration
from swagger_client.models.web_hook_update_v21 import WebHookUpdateV21
